mapping:
  class: AppBundle\Document\Geo
  aliased_properties:
    poi_type: type
  hide_properties: []
#  included_properties:
#      - type
  id_properties:
    - id
  urls:
    self: get_geo ## @Route name
