tagifai_api_route:
    type:        annotation
    resource:    AppBundle\Controller\ApiController
    
tagifai_import_route:
    type:        annotation
    resource:    AppBundle\Controller\ImportController